### ISSUE TITLE
cyrange import can be simplified?

### ISSUE THREAD

**Issue by mentalisttraceur** [maxfischer2781/backports.range#4]
So I'm looking at [this code where `cyrange` is imported](https://github.com/maxfischer2781/backports.range/blob/master/backports/range/pyrange.py#L13-L18), and it seems like it could be simplified, but I might be missing something?

Currently it is like this:
```python
try:
    if platform.python_implementation() != 'CPython':
        raise ImportError
    from .cyrange import range as cyrange  # type: range
except ImportError:
    cyrange = None
```
but couldn't it be simplified like this:
```python
if platform.python_implementation() == 'CPython':
    from .cyrange import range as cyrange  # type: range
else:
    cyrange = None
```

**Comment by maxfischer2781** [comment]
It is possible to use CPython without Cython available. In this case, ``cyrange`` is not available even when running on CPython. The ``ImportError`` check is needed to cover this case.

Since [PyPy's C-API is catching up with the CPython C-API](https://morepypy.blogspot.com/2018/09/inside-cpyext-why-emulating-cpython-c.html), the interpreter check may be worth removing. AFAIK, this is not released yet and PyPy's internal ``range`` optimisations are much better than static optimisation.

**Comment by mentalisttraceur** [comment]
Oh, I get it now. You're saying that the `from .cyrange import range as cyrange` line could fail even if the prior check succeeds, so the check failure and the import attempt failure are *two separate* conditions under which we want the default `cyrange = None` check.

Okay, that wasn't immediately obvious, but I should've done better idea-fitting: I didn't spend enough time thinking "under what circumstances would the extant code behave differently than my proposed simplification?"

Thank you for clarifying! (I'm closing this because you've addressed my question, but of course feel free to re-open if you want to use this issue to keep track of something.)
